[build]
cmd = "go build -o ./tmp/consumer ./cmd/consumer/main.go"
bin = "./tmp/consumer"
include_dir = ["cmd", "internal", "pkg"]
exclude_dir = ["assets", "tmp", "vendor"]

[watch]
include = ["**/*.go"]
exclude = ["**/vendor/**"]